### ISSUE TITLE
[VPNKit+kernel 4.19] CPU 100% on debian stretch

### ISSUE THREAD

**Issue by tonistiigi** [rootless-containers/rootlesskit#44]
On debian stretch I see rootlesskit helper process going to 100% CPU quickly after launching rootless docker.

The process in question: `/proc/self/exe --net=vpnkit --mtu=1500 --disable-host-loopback --copy-up=/etc --copy-up=/run /home/tonis/bin/dockerd-rootless.sh --experimental --iptables=false --storage-driver=vfs` . Afaik we haven't reproduced it in other systems.

```
Linux dev3.localdomain 4.19.0-0.bpo.1-amd64 #1 SMP Debian 4.19.12-1~bpo9+1 (2018-12-30) x86_64 GNU/Linux
```

```
SIGQUIT: quit
PC=0x458d01 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0xb2f8e0, 0x80, 0x0, 0x0, 0x0, 0x4450f7, 0x0, 0x0, 0x7ffee9122d18, 0x40a4d2, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:531 +0x21
runtime.futexsleep(0xb2f8e0, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0xb2f8e0)
	/usr/local/go/src/runtime/lock_futex.go:151 +0xa2
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:2016 +0xe3
runtime.findrunnable(0xc00002a000, 0x0)
	/usr/local/go/src/runtime/proc.go:2487 +0x4dc
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2613 +0x13a
runtime.goexit0(0xc000078480)
	/usr/local/go/src/runtime/proc.go:2790 +0x1f2
runtime.mcall(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x47c8, 0xc000121580, 0x1000004, 0x0, 0x0, 0x60, 0xc00018c180, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc0000265a0, 0x4, 0xc0001216e8, 0xc0000265a0)
	/usr/local/go/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc0000265a0, 0xc00004e700, 0x5313ab, 0x0)
	/usr/local/go/src/os/exec_unix.go:22 +0x39
os.(*Process).Wait(0xc0000265a0, 0x839b68, 0x839b70, 0x839b60)
	/usr/local/go/src/os/exec.go:125 +0x2b
os/exec.(*Cmd).Wait(0xc00016e580, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:465 +0x5b
os/exec.(*Cmd).Run(0xc00016e580, 0x4, 0x4)
	/usr/local/go/src/os/exec/exec.go:309 +0x5c
github.com/rootless-containers/rootlesskit/pkg/child.Child(0x82a62c, 0x20, 0xc0000a0060, 0x4, 0x4, 0xc0000c6600, 0x0, 0x0)
	/tmp/tmp.OaOUjTeq2A/src/github.com/rootless-containers/rootlesskit/pkg/child/child.go:221 +0x295
main.main.func2(0xc0000b6840, 0x0, 0x0)
	/tmp/tmp.OaOUjTeq2A/src/github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:101 +0xd4
github.com/rootless-containers/rootlesskit/vendor/github.com/urfave/cli.HandleAction(0x79dfe0, 0xc0000a8300, 0xc0000b6840, 0x0, 0x0)
	/tmp/tmp.OaOUjTeq2A/src/github.com/rootless-containers/rootlesskit/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/rootless-containers/rootlesskit/vendor/github.com/urfave/cli.(*App).Run(0xc0000ae9c0, 0xc0000a0000, 0xa, 0xa, 0x0, 0x0)
	/tmp/tmp.OaOUjTeq2A/src/github.com/rootless-containers/rootlesskit/vendor/github.com/urfave/cli/app.go:264 +0x59d
main.main()
	/tmp/tmp.OaOUjTeq2A/src/github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:109 +0x93d

goroutine 4 [syscall]:
syscall.Syscall(0x0, 0x3, 0xc00017c000, 0x10000, 0xc0000c6040, 0x0, 0x48eb81)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x3, 0xc00017c000, 0x10000, 0x10000, 0xc0000c6001, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:732 +0x5a
syscall.Read(0x3, 0xc00017c000, 0x10000, 0x10000, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:172 +0x49
internal/poll.(*FD).Read(0xc00009eae0, 0xc00017c000, 0x10000, 0x10000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:165 +0x119
os.(*File).read(0xc00009c118, 0xc00017c000, 0x10000, 0x10000, 0x10000, 0xc00017c000, 0x7f37306175f0)
	/usr/local/go/src/os/file_unix.go:249 +0x4e
os.(*File).Read(0xc00009c118, 0xc00017c000, 0x10000, 0x10000, 0x7918a0, 0x1, 0xc00017c000)
	/usr/local/go/src/os/file.go:108 +0x69
github.com/rootless-containers/rootlesskit/vendor/github.com/jamescun/tuntap.(*device).Read(0xc0000a8e80, 0xc00017c000, 0x10000, 0x10000, 0x10000, 0x10000, 0x0)
	/tmp/tmp.OaOUjTeq2A/src/github.com/rootless-containers/rootlesskit/vendor/github.com/jamescun/tuntap/device_linux.go:26 +0x4d
github.com/rootless-containers/rootlesskit/pkg/network/vpnkit.tap2vif(0xc0000b2be0, 0x7f373061b000, 0xc0000a8e80)
	/tmp/tmp.OaOUjTeq2A/src/github.com/rootless-containers/rootlesskit/pkg/network/vpnkit/vpnkit.go:189 +0x95
created by github.com/rootless-containers/rootlesskit/pkg/network/vpnkit.startVPNKitRoutines
	/tmp/tmp.OaOUjTeq2A/src/github.com/rootless-containers/rootlesskit/pkg/network/vpnkit/vpnkit.go:181 +0x537

goroutine 5 [IO wait]:
internal/poll.runtime_pollWait(0x7f37307c0118, 0x72, 0xc00004c3c8)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000158098, 0x72, 0xffffffffffffff00, 0x8899a0, 0xaf5380)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000158098, 0xc00019a000, 0x2, 0x8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000158080, 0xc00019a008, 0x2, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000158080, 0xc00019a008, 0x2, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00009c120, 0xc00019a008, 0x2, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x68
io.ReadAtLeast(0x7f37307c0530, 0xc00009c120, 0xc00019a008, 0x2, 0x8, 0x2, 0x79be80, 0x1, 0xc00019a008)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(0x7f37307c0530, 0xc00009c120, 0xc00019a008, 0x2, 0x8, 0x0, 0x200, 0x0)
	/usr/local/go/src/io/io.go:329 +0x58
encoding/binary.Read(0x7f37307c0530, 0xc00009c120, 0x88e2a0, 0xb4c508, 0x787360, 0xc00019a000, 0x0, 0x0)
	/usr/local/go/src/encoding/binary/binary.go:171 +0x50a
github.com/rootless-containers/rootlesskit/vendor/github.com/moby/vpnkit/go/pkg/vmnet.(*Vif).Read(0xc0000b2be0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.OaOUjTeq2A/src/github.com/rootless-containers/rootlesskit/vendor/github.com/moby/vpnkit/go/pkg/vmnet/vmnet.go:261 +0xa8
github.com/rootless-containers/rootlesskit/pkg/network/vpnkit.vif2tap(0x7f373061b020, 0xc0000a8e80, 0xc0000b2be0)
	/tmp/tmp.OaOUjTeq2A/src/github.com/rootless-containers/rootlesskit/pkg/network/vpnkit/vpnkit.go:201 +0x2f
created by github.com/rootless-containers/rootlesskit/pkg/network/vpnkit.startVPNKitRoutines
	/tmp/tmp.OaOUjTeq2A/src/github.com/rootless-containers/rootlesskit/pkg/network/vpnkit/vpnkit.go:182 +0x597

rax    0xca
rbx    0xb2f7a0
rcx    0x458d03
rdx    0x0
rdi    0xb2f8e0
rsi    0x80
rbp    0x7ffee9122ce0
rsp    0x7ffee9122c98
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x30
r13    0x11
r14    0x8833a4
r15    0x0
rip    0x458d01
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

@AkihiroSuda

**Comment by AkihiroSuda** [comment]
Could you try slirp4netns mode?

**Comment by tonistiigi** [comment]
Does not reproduce with slirp4netns

**Comment by tonistiigi** [comment]
@AkihiroSuda Did you manage to reproduce it or do you need me to debug more?

**Comment by AkihiroSuda** [comment]
Could not reproduce on Debian stretch (`Linux suda-debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux` with 32 cores)

Wondering this is an issue in vpnkit/go library?
cc @djs55

**Comment by tonistiigi** [comment]
Tried to debug this a bit but looking quite weird.

It goes away as soon as there is some network traffic (pull image etc).

It doesn't seem to be a busy loop in the rootlesskit/vpnkit go code.

When I add a cpu profiler it goes away. The best hint I could read from the profile is the poll happening on reading the tap device(non-vpnkit side) but not sure as mostly the profile was just empty.

When I attach with strace it goes away and there is nothing interesting in the output.

**Comment by tonistiigi** [comment]
If I boot to 4.9 , the issue goes away. So unlikely rootlesskit can do much about it. But haven't found a matching kernel/go issue.
